### ISSUE TITLE
replace thorn with django-channels

### ISSUE THREAD

**Issue by janeeisenstein** [simplworld/simpl-modelservice#19]
It appears thorn has been abandoned at a version that does not support Django 2.2+ compatible simpl-games-api webhooks. Replacing it with django-channels webhooks will allow the simpl-games-api repo to move to Django 2.2+

**Comment by frankwiles** [comment]
We could also do it via Celery and avoid Channels now that I think about it.

**Comment by janeeisenstein** [comment]
Wouldn't that complicate deployments for everyone?

**Comment by janeeisenstein** [comment]
After discussion, this is not the direction we'll be taking to fix webhooks.
