### ISSUE TITLE
Move AWS profiler instance management to another repository

### ISSUE THREAD

**Issue by frankwiles** [simplworld/simpl-modelservice#32]
The AWS profiling code only makes sense for the Wharton School and doesn't have any use in simpl-modelservice on it's own.  Would remove a couple of dependencies and reduce bloat.

**Comment by janeeisenstein** [comment]
Why wouldn't another team be able to use the profiling. It's not specific to Wharton.

**Comment by frankwiles** [comment]
Everything about it assumes a certain setup, with certain tagged EC2 instances, setup in a certain way.  It's not generic at all really.

**Comment by janeeisenstein** [comment]
I agree the remote server instance scripts/docs are Wharton specific. The core code though can be run locally and from that basis site-specific remote server scripts written. So, let's just move the Wharton-specific remote server code to a Wharton repo and provide decent documentation on how to use the core code.

**Comment by janeeisenstein** [comment]
I don't believe any of the profiling code needs to be part of the `simpl-modelservice` repo. How about moving the core profiling code to a new `simpl-profiling` repo? That way it is available to Simpl implementers who want to load test their model service.

**Comment by janeeisenstein** [comment]
Renaming this issue clarified the scope of requested changes.

**Comment by ghost** [comment]
Completed in version 0.10.1
